---
- name: install JRE
  hosts: nexus_server
  tasks:
    - name: update apt repo and cache
      apt: update_cache=yes cache_valid_time=3600
    - name: install java jre
      apt:
        name: default-jre-headless

- name: download and unpack nexus
  hosts: nexus_server
  tasks:
    - name: download nexus
      get_url:
        url: https://download.sonatype.com/nexus/3/nexus-3.88.0-08-linux-aarch_64.tar.gz
        dest: /opt/
      register: download_result
    - name: check if nexus folder already exists
      stat:
        path: /opt/nexus
      register: stat_result
    - name: untar nexus installer
      unarchive:
        src: "{{ download_result.dest }}"
        dest: /opt
        remote_src: true
      when: not stat_result.stat.exists
    - name: find nexus directory
      find:
        paths: /opt
        pattern: "nexus-*"
        file_type: directory
      register: find_result
    - name: rename nexus directory
      shell: mv {{find_result.files[0].path}} /opt/nexus
      when: not stat_result.stat.exists

- name: create nexus user to own nexus directory
  hosts: nexus_server
  tasks:
    - name: ensure nexus group exists
      group:
        name: nexus
        state: present
    - name: create nexus user
      user:
        name: nexus
        group: nexus
    - name: make nexus user the owner of nexus directory
      file:
        path: /opt/nexus
        state: directory
        owner: nexus
        group: nexus
        recurse: yes
    - name: make nexus user the owner of nexus sonatype-work directory
      file:
        path: /opt/sonatype-work
        state: directory
        owner: nexus
        group: nexus
        recurse: yes

- name: start nexus with nexus user
  hosts: nexus_server
  become: true
  become_user: nexus
  tasks:
    - name: set run_as_user for nexus
      lineinfile:
        path: /opt/nexus/bin/nexus
        regexp: '^#?\s*run_as_user='
        line: 'run_as_user="nexus"'
    - name: start nexus
      command: /opt/nexus/bin/nexus start

- name: verify if nexus is running
  hosts: nexus_server
  tasks:
    - name: check with present
      shell: ps aux | grep nexus
      register: app_status
    - debug: msg={{ app_status.stdout_lines }}
    - name: wait 1 minute
      pause:
        minutes: 1
    - name: check with ss
      shell: ss -ntulp
      register: app_status
    - debug: msg={{ app_status.stdout_lines }}



